projects:
  find-it:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        region: us-east-2
        apiId: sl2a747nargi5fg3nflpqck66a
        maxDepth: 2
extensions:
  amplify:
    version: 3
